CMD_PING = 1
CMD_ECHO = 3
CMD_LOGIN = 5
CMD_LIST = 10
CMD_MSG = 15
CMD_FILE = 20
CMD_RECEIVE_MSG = 25
CMD_RECEIVE_FILE = 30

# Responses
CMD_PING_RESPONSE = 2
CMD_LOGIN_OK_NEW = 6 
CMD_LOGIN_OK = 7 
CMD_MSG_SENT = 16
CMD_FILE_SENT = 21
CMD_RECEIVE_MSG_EMPTY = 26
CMD_RECEIVE_FILE_EMPTY = 31

# Errors
SERVER_ERROR = 100
INCORRECT_CONTENT_SIZE = 101
SERIALIZATION_ERROR = 102
INCORRECT_COMMAND = 103
WRONG_PARAMS = 104

LOGIN_WRONG_PASSWORD = 110
LOGIN_FIRST = 111
FAILED_SENDING = 112